<template>
  <div>
    <sections-intro></sections-intro>
    <sections-typography></sections-typography>
    <sections-colors></sections-colors>
    <sections-borders></sections-borders>
    <sections-sizing></sections-sizing>
    <sections-spacing></sections-spacing>
    <sections-breakpoints></sections-breakpoints>
    <sections-states></sections-states>
    <sections-flex></sections-flex>
    <sections-grid></sections-grid>
  </div>
</template>
