<template>
  <div>
    <sections-intro></sections-intro>
    <sections-typography></sections-typography>
    <sections-colors></sections-colors>
    <sections-borders></sections-borders>
    <sections-sizing></sections-sizing>
  </div>
</template>
